version: "3.1"

services:
  app:
    image: messiasmrt/django-react-sample
    build: .
    # load connection strings / secrets from the .env file
    env_file:
      - .env
    ports:
      - 8000:8000
    links:
      - db

  # for testing against a local database
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
